title: TypoTab
description: Blogs and articles about all things typography! At typotab we delve
  deeper into the hidden meaning behind the typography used in all aspects of
  life!
header_text: ""
footer_text: Copyright 2020 Chloe Meek
header_feature_image: ../uploads/screenshot-2020-10-11-at-15.59.29.png
bannerheight: 20vmax
logo: ../uploads/screenshot-2020-10-11-at-16.35.14.png
favicon: ../uploads/typotab-logo-2.png
gridlayout: true
fixednavbar: false
upzoom: true
