title: typotab
description: Blogs and articles about all things typography! At typotab we delve
  deeper into the hidden meaning behind the typography used in all aspects of
  life!
header_text: Talking All Things Typography!
footer_text: Copyright 2020 Chloe Meek
header_feature_image: ../uploads/screenshot-2020-09-21-at-17.07.44.png
bannerheight: 20vmax
logo: ../uploads/screenshot-2020-09-21-at-17.04.19.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
